apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-leaderboard
  namespace: devteamtools
  labels:
    app: pr-leaderboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pr-leaderboard
  template:
    metadata:
      labels:
        app: pr-leaderbaord
    spec:
      containers:
      - name: pr-leaderboard
        image: devteamtools/pr-leaderboard:LATEST
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: 250m
              memory: 128m
---
apiVersion: v1
kind: Service
metadata:
  name: pr-leaderboard
  namespace: devteamtools
spec:
  selector:
    app: pr-leaderboard
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
