apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-leaderboard-api
  namespace: devteamtools
  labels:
    app: pr-leaderboard-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pr-leaderboard-api
  template:
    metadata:
      labels:
        app: pr-leaderboard-api
    spec:
      containers:
      - name: pr-leaderboard
        image: devteamtools/pr-leaderboard:900d519b
        ports:
        - containerPort: 8080
        env:
        - name: STORE_TYPE
          value: redis
        - name: REDIS_ADDRESS
          value: redis:6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: devteamtools
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: pr-leaderboard-api
  namespace: devteamtools
spec:
  selector:
    app: pr-leaderboard-api
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: devteamtools
spec:
  selector:
    app: redis
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-pr-leaderboard
  namespace: devteamtools
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: pr-leaderboard.devteamtools.org
    http:
      paths:
      - path: /api*
        backend:
          serviceName: pr-leaderboard-api
          servicePort: 8080
      - path: /github*
        backend:
          serviceName: pr-leaderboard-api
          servicePort: 8080
