apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-leaderboard
  labels:
    app: pr-leaderboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pr-leaderboard
    spec:
      containers:
      - name: pr-leaderboard
        image: devteamtools/pr-leaderboard:0.1
        env:
          PORT: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pr-leaderboard
spec:
  selector:
    app: pr-leaderboard
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
