apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-leaderboard
  namespace: devteamtools
  labels:
    app: pr-leaderboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pr-leaderboard
  template:
    metadata:
      labels:
        app: pr-leaderboard
    spec:
      containers:
      - name: nginx
        image: devteamtools/pr-leaderboard:LATEST
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pr-leaderboard
  namespace: devteamtools
spec:
  type: LoadBalancer
  selector:
    app: pr-leaderboard
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
