apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-leaderboard
  namespace: devteamtools
  labels:
    app: pr-leaderboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pr-leaderboard
  template:
    metadata:
      labels:
        app: pr-leaderboard
    spec:
      containers:
      - name: nginx
        image: devteamtools/pr-leaderboard:LATEST
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pr-leaderboard
  namespace: devteamtools
spec:
  selector:
    app: pr-leaderboard
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-pr-leaderboard
  namespace: devteamtools
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: pr-leaderboard.devteamtools.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: pr-leaderboard
          servicePort: 8080
